### PR TITLE
Add ability to get my recipes

### PR DESCRIPTION
**Pull request by davidclaeysquinones**
The webapp offers the ability to make your custom recipes.
I've modified the existing code so that these can be gathered.

### CODE REVIEW

**Comment by miaucl** [comment]
Hey, thank you for your interest. I am currently working on the same on this branch which will let one manage the collections (managed and custom). I think this will cover also the content of this PR. 
https://github.com/miaucl/cookidoo-api/tree/collections

**Comment by davidclaeysquinones** [comment]
I didn't notice you already were working on it. Looking forward to see those changes implemented ;)

**Comment by miaucl** [comment]
@davidclaeysquinones Is this still relevant, I referenced another PR about the recipes and collections.

**Comment by davidclaeysquinones** [comment]
You've made a better versión of what I've made.
My PR pales in comparisson.
I think that you just can cancel it.

**Pull request closed without merging**
